---
title: "01_input_data_processing"
author: "Stefan Fallert"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the required packages

```{r load-required-pacakges, include=FALSE}
library(here)
library(raster)
library(tidyverse)
library(rgbif)
```

define what species are studied

```{r}
species_names <- c("Alchemilla alpina L.")#, "Cerastium cerastoides"
```

load data from gbif
```{r}
here::here()
gbif_data <- occ_data(scientificName = species_names, hasCoordinate = TRUE, limit = 200000, gadmGid = "DEU.2_1")  # note that coordinate ranges must be specified this way: "smaller, larger" (e.g. "-5, -2")
# get the columns that matter for mapping and cleaning the occurrence data:
mylist.names <- c("scientificName", "decimalLongitude", "decimalLatitude",  "references")
locations_gbif <- NULL
locations_gbif[mylist.names] <- list(NULL)

if (length(species_names)>1){
  for (sp in 1:length(species_names)){
    locations_gbif <- Map(c,locations_gbif,gbif_data[[sp]]$data[ , c("scientificName", "decimalLongitude", "decimalLatitude",  "references")])
  }
  names(locations_gbif) <- c("species", "lon", "lat", "ref")
  locations_gbif <- do.call(cbind.data.frame, locations_gbif)
}
if (length(species_names)==1){
locations_gbif <- Map(c,locations_gbif,gbif_data$data[ , c("scientificName", "decimalLongitude", "decimalLatitude",  "references")])
names(locations_gbif) <- c("species", "lon", "lat", "ref")
  locations_gbif <- do.call(cbind.data.frame, locations_gbif)
}
```

```{r shapefile}
# Germany <- getData("GADM", country="DE",level=1)
# Bavaria <- Germany[Germany@data$NAME_1 == "Bayern", ]
```




parse the classes
```{r}
save_file_name<-here("data/land_use_classes.csv")
if(file.exists(save_file_name)){
  codes <- read.csv(save_file_name)
} else {
  codes <- read.delim(here("data/clc_2018/clc_legend_qgis_raster.qml"))
  names(codes) <- "text"
  codes <- codes %>%
    filter(str_detect(text, "paletteEntry "))
  codes$label <- NA
  codes$name <- NA
  codes$value <- NA
  
  for (i in 1:nrow(codes)) {
    split_val <- strsplit(gsub(" - ", "%", strsplit(codes[i, "text"], "=")[[1]][3]), "%")[[1]]
    codes[i, "label"] <- trimws(split_val[1])
    codes[i, "name"] <- trimws(gsub(" value", "", split_val[2]))
    split_val <- strsplit(gsub(" alpha", "", codes[i, "text"]), "=")[[1]]
    codes[i, "value"] <- split_val[length(split_val) - 1]
  }
  rm(i)
  rm(split_val)
  # write.csv(codes, here("data/land_use_classes.csv"), row.names = F)
  # write.table(codes, here("data/land_use_classes.txt"),
  #             row.names = F
  # )
  write.csv(codes, "/home/jab50ej/Dokumente/land_use_classes.txt", row.names = F)
}
```


Read in the current clc / land use data and generate how suitable they are for each species
```{r}
#save_file_name<-here("data/land_use_classes_suitability_per_Species.csv")
save_file_name<-"/home/jab50ej/Dokumente/land_use_classes_suitability_per_Species.csv"
if(file.exists(save_file_name)){
  clc_freq <- read.csv(save_file_name)
} else {
  
  clc_files <- list.files(here("data/clc_2018"), "class*.*tif", full.names = T)
  
  clc_freq <- codes[, -1]
  clc_freq <- expand_grid(clc_freq, species_names)
  clc_freq$freq <- NA
  
  for (sp in unique(clc_freq$species_names)) {
    location_sp <- locations_gbif[locations_gbif$species == sp, ]
    #location_sp <- locations_gbif %>% filter(grepl(sp, species))
    for (clc in clc_files) {
      freq <- raster::extract(raster(clc), location_sp[, c("lon", "lat")])
      index <- clc_freq$value == as.numeric(strsplit(basename(clc), "-")[[1]][2]) & clc_freq$species_names == sp
      clc_freq[index, "freq"] <- mean(freq, na.rm = T)
    }
  }
  
  # exclude unlikely results and water classes
  clc_freq <- clc_freq %>%
    mutate(freq = replace(freq, freq < 1 | is.na(freq) | value >= 40, 0))
  
  # Calculate habitability value
  clc_freq = clc_freq %>% group_by(species_names) %>% mutate(habit_val = freq/max(freq))
  # max_freq <- clc_freq %>%
  #   group_by(species_names) %>%
  #   summarize(m = max(freq, na.rm = T))
  # 
  # clc_freq$habit_val <- NA
  # for (i in 1:nrow(clc_freq)) {
  #   clc_freq$habit_val[i] <- 
  #     clc_freq$freq[i] / max_freq$m[
  #       max_freq$species_names == clc_freq$species_names[i]
  #     ]
  #}
  
  write.csv(clc_freq, "/home/jab50ej/Dokumente/land_use_classes_suitability_per_Species.csv", row.names = F)
  write.table(clc_freq, "/home/jab50ej/Dokumente/land_use_classes_suitability_per_Species.txt",
              row.names = F
  )
}
```



Read in the biotope data and see how suitable they are for each species
```{r}
save_file_name<-"/home/jab50ej/Dokumente/biotope_suitability_per_Species.csv"
if(file.exists(save_file_name)){
  biotope_freq <- read.csv(save_file_name)
} else {
  
  biotope_files <- list.files(here("data/potential_biotopes_2018-2100"), "*.*gri")
  biotope_freq <- do.call(rbind.data.frame, str_split(biotope_files, "_"))
  names(biotope_freq) <- c("scenario", "rcp", "biotope", "notused")
  biotope_freq$notused <- NULL
  
  biotope_freq <- expand_grid(biotope_freq, species_names)
  biotope_freq$freq <- NA
  
  biotope_files <- list.files(here("data/potential_biotopes_2018-2100"), "*.*gri", full.names = T)
  for (i in 1:nrow(biotope_freq)) {
    location_sp <- locations_gbif[locations_gbif$species == biotope_freq$species_names[i], ]
    
    filename <- grep(biotope_freq$biotope[i], biotope_files, value = T)
    filename <- grep(biotope_freq$scenario[i], filename, value = T)
    filename <- grep(biotope_freq$rcp[i], filename, value = T)
    
    r <- raster(filename, band = 1)
    freq <- raster::extract(r, location_sp[, c("lon", "lat")])
    biotope_freq[i, "freq"] <- mean(freq, na.rm = T)
  }
  
  # Calculate habitability value
  max_freq <- biotope_freq %>%
    group_by(species_names, scenario, rcp) %>%
    summarize(m = max(freq, na.rm = T))
  
  biotope_freq$habit_val <- NA
  for (i in 1:nrow(biotope_freq)) {
    biotope_freq$habit_val[i] <- 
      biotope_freq$freq[i] / max_freq$m[
        max_freq$species_names == biotope_freq$species_names[i] &
          max_freq$scenario == biotope_freq$scenario[i] &
          max_freq$rcp == biotope_freq$rcp[i]
      ]
  }
  write.csv(biotope_freq, "/home/jab50ej/Dokumente/biotope_suitability_per_Species.csv", row.names = F)
  write.table(biotope_freq, "/home/jab50ej/Dokumente/biotope_suitability_per_Species.txt",
              row.names = F
  )
}
```


now the climate files 
note: may have to change the bioclim variables that are used (10&18 currently)
```{r}
#save_file_name<-here("data/climate.csv")
save_file_name<-"/home/jab50ej/Dokumente/climate.csv"
if(file.exists(save_file_name)){
  biotope_freq <- read.csv(save_file_name)
} else {
  climate_files <- list.files(here("data/bioclim_2018-2100"), "*.*gri", full.names = T, recursive = T)
  climate <- unique(biotope_freq[, c(1, 2, 4)])
  
  climate$median <- NA
  climate$mean <- NA
  climate$kdemax <- NA
  climate$min <- NA
  climate$max <- NA
  
  climate_var<-data.frame(id=c("bio1","bio12"),
                          id_label=c("Mean Annual Temperature",
                                     "Annual Precipitation"),
                          id_num=c(1,12))
  climate <- expand_grid(climate, climate_var)
  
  for (i in 1:nrow(climate)) {
    location_sp <- locations_gbif[locations_gbif$species == climate$species_names[i], ]
    
    filename <- grep(climate$scenario[i], climate_files, value = T)
    filename <- grep(climate$rcp[i], filename, value = T)
    filename <- grep("1981", filename, value = T)
    
    bio <- raster(filename, band = climate$id_num[i])
    bio <- resample(bio, r, method='bilinear')
    bio <- raster::extract(bio, location_sp[, c("lon", "lat")])
    
    climate[i,"median"] <- median(bio)
    climate[i,"mean"] <- mean(bio)
    climate[i,"kdemax"] <- density(bio)$x[which.max(density(bio)$y)]
    climate[i,"min"] <- min(bio)
    climate[i,"max"] <- max(bio)
    
  }
  
  write.csv(climate, "/home/jab50ej/Dokumente/climate.csv", row.names = F)
  write.table(climate, "/home/jab50ej/Dokumente/climate.txt",
              row.names = F
  )
}
```

```{r session-info}
sessionInfo()
```
